# Numpy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([1,6,3,4,9])
print(a)
print(b)

[1 2 3 4 5]
[1 6 3 4 9]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [14]:
# Dimensions
a = np.array([[1,2,3], [4,5,6]])
print(a.ndim)
print(a[1,2])
print(a[0,0])
print(a[1,1])
print(a)

2
6
1
5
[[1 2 3]
 [4 5 6]]


In [15]:
b = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print(b.ndim)              
print(b)

3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
print(b[0,0,1])

2
